version: "3.7"

services:
  intiface:
    devices:
      - "/dev/bus/usb/FILL_IN_HERE:/dev/ttyUSB0" # TODO cgroup permissions?
    network_mode: "host"
    privileged: true
    restart: unless-stopped
    build: .
    ports:
      - "12345:12345"
    cap_add:
      - SYS_ADMIN
